# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  dir:  # id of input
    description: 'List of files'
    required: true
    default: './'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  # DOCKER ACTION
  #  using: 'docker'
  #  image: 'Dockerfile'
  #  args:
  #    - ${{ inputs.dir }}
  
  # JS ACTION
  # using: 'node12'
  # main: 'index.js'
  
  # COMPOSITE ACTION (bash)
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo "Listing of directory ${{ inputs.dir }}" && ls -la ${{ inputs.dir }}
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
